# Generated by Django 3.1.3 on 2020-11-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_text_reviews_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(blank=True),
        ),
    ]
